version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 835247
      POSTGRES_DB: nestjs
    ports:
      - "5432:5432"
    # Sem volumes para não persistir os dados

  backend:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 835247
      DATABASE_NAME: nestjs
    ports:
      - "3000:3000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5