version: '3'
service:
  postgres:
    image: postgres
    restart: always
    environment:
      -
      -
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      -
    volumes:
      